# Generated by Django 3.1.2 on 2021-02-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareitsuser',
            name='bgimg',
            field=models.ImageField(default='0', upload_to='shop/bg'),
        ),
        migrations.AlterField(
            model_name='shareitsuser',
            name='image',
            field=models.ImageField(default='1', upload_to='shop/userimg'),
        ),
    ]
