# Generated by Django 3.1.2 on 2021-03-10 13:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0003_profile_relationship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='friends',
        ),
        migrations.RemoveField(
            model_name='shareitsuser',
            name='pass1',
        ),
        migrations.RemoveField(
            model_name='shareitsuser',
            name='pass2',
        ),
        migrations.AddField(
            model_name='shareitsuser',
            name='bio',
            field=models.TextField(default='no bio...', max_length=300),
        ),
        migrations.AddField(
            model_name='shareitsuser',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RemoveField(
            model_name='shareitsuser',
            name='Userfriends',
        ),
        migrations.AddField(
            model_name='shareitsuser',
            name='Userfriends',
            field=models.ManyToManyField(blank=True, related_name='friends', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shareitsuser',
            name='email',
            field=models.EmailField(blank=True, max_length=200),
        ),
    ]
